version: '3.9'

services:
  ui: 
    container_name: tic-tac-toe-gui
    image: tic-tac-toe-gui
    environment: 
      - BROWSER=none
      - NODE_ENV=development
    build:
      context: ./tic-tac-toe-gui
      dockerfile: Dockerfile
    volumes: 
      - ./tic-tac-toe-gui:/app
      - /app/node_modules
    ports:
      - 3000:3000
  
  api:
    container_name: tic-tac-toe-api
    image: tic-tac-toe-api
    build:
      context: ./TicTacToe/TicTacToe
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    expose:
      - "5000"
    environment: 
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - db

  nginx: 
    container_name: nginx
    depends_on: 
      - ui
      - api
    ports: 
      - "81:80"
    build:
      context: ./nginx

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'TicTacToeDB'
      MYSQL_USER: 'TicTacToeAdmin'
      MYSQL_PASSWORD: 'TicTacToeAdminPassword'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./DB/schema.sql:/docker-entrypoint-initdb.d/init.sql

