version: '3.9'

services:
  ui: 
    container_name: tic-tac-toe-gui
    image: tic-tac-toe-gui
    build:
      context: ./tic-tac-toe-gui
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  
  api:
    container_name: tic-tac-toe-api
    image: tic-tac-toe-api
    build:
      context: ./TicTacToe/TicTacToe
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    expose:
      - "5000"
    environment: 
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - db

  nginx: 
    container_name: nginx
    depends_on: 
      - ui
      - api
    ports: 
      - "82:82"
    build:
      context: ./nginx

